/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.matlog.bool4j.interfacepc;

import com.danilov.bool4j.util.Util;
import com.danilov.bool4j.util.VariablesSet;
import com.danilov.converter.Converter;
import com.danilov.converter.SDNFConverter;
import com.danilov.converter.JPolynomConverter;
import com.danilov.converter.SKNFConverter;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import ru.matlog.bool4j.closures.ClosureClass;
import ru.matlog.bool4j.closures.ClosureClasses;
import ru.matlog.bool4j.expression.Calculable;
import ru.matlog.bool4j.expression.Expression;
import ru.matlog.bool4j.expression.RecursiveCalculableFactoryImpl;
import ru.matlog.bool4j.expression.operator.Operators;
import ru.matlog.bool4j.parser.Parser;
import ru.matlog.bool4j.parser.RecursiveParserImpl;

/**
 *
 * @author Эдуард
 */
public class BoolInterface extends javax.swing.JFrame {

    /**
     * Creates new form BoolInterface
     */
    public BoolInterface() {
        initComponents();
        jTabbedPane1.setVisible(false);
        jScrollPane3.setVisible(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoolInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoolInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoolInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoolInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoolInterface().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonDis = new javax.swing.JButton();
        jButtonCon = new javax.swing.JButton();
        jButtonImp = new javax.swing.JButton();
        jButtonEql = new javax.swing.JButton();
        jButtonXor = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        jButtonLbr = new javax.swing.JButton();
        jButton1Rbr = new javax.swing.JButton();
        tableButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jButtonBackspace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bool4j");
        setMinimumSize(new java.awt.Dimension(735, 560));

        jTextField1.setToolTipText("Введите сюда желаемое логическое выражение");

        jButtonDis.setText("Дизъюнкция");
        jButtonDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisActionPerformed(evt);
            }
        });

        jButtonCon.setText("Конъюнкция");
        jButtonCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConActionPerformed(evt);
            }
        });

        jButtonImp.setText("Импликация");
        jButtonImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImpActionPerformed(evt);
            }
        });

        jButtonEql.setText("Эквиваленция");
        jButtonEql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqlActionPerformed(evt);
            }
        });

        jButtonXor.setText("XOR");
        jButtonXor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXorActionPerformed(evt);
            }
        });

        jButtonX.setText("X");
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });

        jButtonY.setText("Y");
        jButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYActionPerformed(evt);
            }
        });

        jButtonZ.setText("Z");
        jButtonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZActionPerformed(evt);
            }
        });

        jButtonLbr.setText("(");
        jButtonLbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLbrActionPerformed(evt);
            }
        });

        jButton1Rbr.setText(")");
        jButton1Rbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RbrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonDis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEql)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonXor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLbr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1Rbr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonZ)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonDis)
                .addComponent(jButtonCon)
                .addComponent(jButtonImp)
                .addComponent(jButtonEql)
                .addComponent(jButtonXor)
                .addComponent(jButtonX)
                .addComponent(jButtonY)
                .addComponent(jButtonZ)
                .addComponent(jButtonLbr)
                .addComponent(jButton1Rbr))
        );

        tableButton.setText("Анализировать выражение");
        tableButton.setToolTipText("Построить таблицу истинности соответствующую данному логическому выражению, найти КНФ и ДНФ");
        tableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableButtonActionPerformed(evt);
            }
        });

        jTabbedPane1.setToolTipText("Таблица истинности");
        jTabbedPane1.setName(""); // NOI18N

        jScrollPane2.setToolTipText("Таблица истинности в виде таблицы");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTabbedPane1.addTab("Таблица истинности", jScrollPane2);

        jScrollPane1.setToolTipText("Таблица истинности выражения, СКНФ, СДНФ в виде текстового файла");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTabbedPane1.addTab("Результат анализа", jScrollPane1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        jTextArea2.setFocusable(false);
        jTextArea2.setOpaque(false);
        jTextArea2.setRequestFocusEnabled(false);
        jTextArea2.setVerifyInputWhenFocusTarget(false);
        jScrollPane3.setViewportView(jTextArea2);

        jButton10.setText("▒");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButtonBackspace.setText("<-");
        jButtonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackspaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBackspace)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBackspace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableButton)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        tableButton.getAccessibleContext().setAccessibleDescription("Построить таблицу истинности соответствующую данному логическому выражению, найти СКНФ и СДНФ");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Parser p = new RecursiveParserImpl();
    private void tableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableButtonActionPerformed

        String input = jTextField1.getText();
        input = input.trim();
        if (!input.equals("")) {
            //System.out.println(input.split("(").length+ " " + input.split(")").length);

            if (Util.bracketValidator(input)) {
                try {
                    updateResult();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Сёма уже работает над этой исправлением ошибки! Или Макс. Или Эдик.",
                            "Известная ошибка!",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Скобка, скобка, скобка... (",
                        "Ошибка ввода!",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Пустое поле ввода",
                    "Ошибка ввода!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tableButtonActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (jPanel1.isVisible()) {
            jPanel1.setVisible(false);
        } else {
            jPanel1.setVisible(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisActionPerformed
        insertIntoInputField(Operators.DISJUNCTION.REPRESENTATION);
    }//GEN-LAST:event_jButtonDisActionPerformed

    private void jButtonConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConActionPerformed
        insertIntoInputField(Operators.CONJUNCTION.REPRESENTATION);
    }//GEN-LAST:event_jButtonConActionPerformed

    private void jButtonImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImpActionPerformed
        insertIntoInputField(Operators.IMPLICATION.REPRESENTATION);
    }//GEN-LAST:event_jButtonImpActionPerformed

    private void jButtonEqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqlActionPerformed
        insertIntoInputField(Operators.EQUAL.REPRESENTATION);
    }//GEN-LAST:event_jButtonEqlActionPerformed

    private void jButtonXorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXorActionPerformed
        insertIntoInputField(Operators.XOR.REPRESENTATION);
    }//GEN-LAST:event_jButtonXorActionPerformed

    private void jButtonLbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLbrActionPerformed
        insertIntoInputField("(");
    }//GEN-LAST:event_jButtonLbrActionPerformed

    private void jButton1RbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RbrActionPerformed
        insertIntoInputField(")");
    }//GEN-LAST:event_jButton1RbrActionPerformed

    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        insertIntoInputField("x");
    }//GEN-LAST:event_jButtonXActionPerformed

    private void jButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYActionPerformed
        insertIntoInputField("y");
    }//GEN-LAST:event_jButtonYActionPerformed

    private void jButtonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZActionPerformed
        insertIntoInputField("z");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonZActionPerformed

    private void jButtonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackspaceActionPerformed
        if (jTextField1.getText().length() > 0) {
            jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getText().length() - 1));
        }
    }//GEN-LAST:event_jButtonBackspaceActionPerformed

    private void updateResult() {
        jTabbedPane1.setVisible(true);
        jScrollPane3.setVisible(true);
        Expression exp = p.parse(jTextField1.getText());
        String result = new String();
        String result2 = new String();
        result += ("Выражение: " + exp.toString() + "\n\nТаблица истинности:\n");
        Parser p = new RecursiveParserImpl();

        Calculable calc = exp.toCalculable(new RecursiveCalculableFactoryImpl());
        VariablesSet varSet = new VariablesSet(calc.getVariableNames());
        List<String> vv = varSet.getKeySet();
        String[] title = new String[vv.size() + 1];
        String[][] results = new String[(int) Math.pow(2, vv.size())][vv.size() + 1];
        int i = 0;
        for (String key : vv) {
            title[i++] = key;
            result += (key + " ");
        }
        title[i] = "Результат";

        result += ("f\n");

        int x = 0;
        int y = 0;


        int row = jTable1.getSelectedRow();

        int j = 0;
        while (varSet.notEnd()) {
            Map<String, Boolean> m = varSet.get();
            calc.with(m);

            for (String key : vv) {
                Boolean var = m.get(key);
                String s;
                if (var) {
                    s = "1";
                } else {
                    s = "0";
                }
                //System.out.println(y+":"+x+"="+s);
                results[y][x++] = s;
                result += (s + " ");
            }

            if (row == j) {
            }


            Boolean val = calc.calculate();
            String s;
            if (val) {
                s = "1";

            } else {
                s = "0";

            }
            results[y++][x] = s;
            x = 0;
            result += (s + "\n");
            result += ("");
            varSet.moveToNext();
            j++;
        }

        Map<String, Boolean> m = varSet.get();
        ClosureClass cc = ClosureClasses.getClosureClass("T0");
        result += ("\nT0: " + cc.whetherBelongs(exp, m));
        result2 += ("T0: " + cc.whetherBelongs(exp, m));
        cc = ClosureClasses.getClosureClass("T1");
        result += ("\n\nT1: " + cc.whetherBelongs(exp, m));
        result2 += ("\n\nT1: " + cc.whetherBelongs(exp, m));
        cc = ClosureClasses.getClosureClass("S");
        result += ("\n\nS: " + cc.whetherBelongs(exp, m));
        result2 += ("\n\nS: " + cc.whetherBelongs(exp, m));
        cc = ClosureClasses.getClosureClass("M");
        result += ("\n\nM: " + cc.whetherBelongs(exp, m));
        result2 += ("\n\nM: " + cc.whetherBelongs(exp, m));


        Converter c = new SDNFConverter();
        Expression exp1 = c.convert(exp);
        if (exp1 != null) {
            result += ("\n\nСДНФ: " + exp1.toString());
            result2 += ("\n\nСДНФ: " + exp1.toString());
        }
        c = new SKNFConverter();
        exp1 = c.convert(exp);
        if (exp1 != null) {
            result += ("\n\nСКНФ: " + exp1.toString());
            result2 += ("\n\nСКНФ: " + exp1.toString());
        }
        c = new JPolynomConverter();
        exp1 = c.convert(exp);
        if (exp1 != null) {
            result += ("\n\nЖегалкин: " + exp1.toString());
            result2 += ("\n\nЖегалкин: " + exp1.toString());
        }







        jTextArea1.setText(result);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                results,
                title) {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });

        jTextArea2.setText(result2);
        jScrollPane2.setViewportView(jTable1);
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        updateResult();
    }//GEN-LAST:event_jTable1MouseClicked

    private void insertIntoInputField(String s) {
        jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getSelectionStart()) + s + jTextField1.getText().substring(jTextField1.getSelectionStart(), jTextField1.getText().length()) + " ");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton1Rbr;
    private javax.swing.JButton jButtonBackspace;
    private javax.swing.JButton jButtonCon;
    private javax.swing.JButton jButtonDis;
    private javax.swing.JButton jButtonEql;
    private javax.swing.JButton jButtonImp;
    private javax.swing.JButton jButtonLbr;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonXor;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton tableButton;
    // End of variables declaration//GEN-END:variables
}